apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${APP_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  serviceName: ${APP_NAME}
  replicas: ${K8S_REPLICAS}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: main
        image: "harbor.cluster.home.sanlea.com/study/${APP_NAME}:${APP_VERSION}"
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ${K8S_STORAGE_CLASS_NAME}
      resources:
        requests:
          storage: ${K8S_STORAGE_SIZE}