apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${K8S_SERVICE_NAME}
spec:
  selector:
    matchLabels:
      app: ${K8S_SERVICE_NAME}
  serviceName: ${K8S_SERVICE_NAME}
  replicas: ${K8S_REPLICAS}
  template:
    metadata:
      labels:
        app: ${K8S_SERVICE_NAME}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: main
        image: "harbor.cluster.home.sanlea.com/study/${APP_NAME}:${APP_VERSION}"
        resources:
          requests:
            cpu: ${K8S_REQUEST_CPU}
            memory: ${K8S_REQUEST_MEMORY}
          limits:
            cpu: ${K8S_LIMIT_CPU}
            memory: ${K8S_LIMIT_MEMORY}
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ${K8S_STORAGE_CLASS_NAME}
      resources:
        requests:
          storage: ${K8S_STORAGE_SIZE}